-- credits to 96flashbacks and qett

local SoundTable = {
	MARIO_ATTACKED = script.MARIO_ATTACKED,
	MARIO_DOH = script.MARIO_DOH,
	MARIO_GROUND_POUND_WAH = script.MARIO_GROUND_POUND_WAH,
	MARIO_HAHA = script.MARIO_HAHA,
	MARIO_HOO = script.MARIO_HOO,
	MARIO_HOOHOO = script.MARIO_HOOHOO,
	MARIO_IMA_TIRED = script.MARIO_IMA_TIRED,
	MARIO_MAMA_MIA = script.MARIO_MAMA_MIA,
	MARIO_ON_FIRE = script.MARIO_ON_FIRE,
	MARIO_OOOF = script.MARIO_OOOF,
	MARIO_PANTING = script.MARIO_PANTING,
	MARIO_PUNCH_YAH = script.MARIO_PUNCH_YAH,
	MARIO_PUNCH_WAH = script.MARIO_PUNCH_WAH,
	MARIO_PUNCH_HOO = script.MARIO_PUNCH_HOO,
	MARIO_SNORING1 = script.MARIO_SNORING1,
	MARIO_SNORING2 = script.MARIO_SNORING2,
	MARIO_SNORING3 = script.MARIO_SNORING3,
	MARIO_UH = script.MARIO_UH,
	MARIO_UH2 = script.MARIO_UH2,
	MARIO_WAAAOOOW = script.MARIO_WAAAOOOW,
	MARIO_WAH = script.MARIO_WAH,
	MARIO_WAHA = script.MARIO_WAHA,
	MARIO_WHOA = script.MARIO_WHOA,
	MARIO_YAH = script.MARIO_YAH,
	MARIO_YAHOO = script.MARIO_YAHOO,
	MARIO_YAWNING = script.MARIO_YAWNING,
	MARIO_YIPPEE = script.MARIO_YIPPEE,
	
	-- MARIO_JUMP = script.MARIO_JUMP,
	-- MARIO_YAH_WAH_HOO = script.MARIO_YAH_WAH_HOO,
	-- MARIO_YAHOO_WAHA_YIPPEE = script.MARIO_YAHOO_WAHA_YIPPEE,
} :: {[string]: Sound | Configuration}

return SoundTable