--[[

https://github.com/sm64js/sm64js/blob/04c1a984117ebb8d0e7b0d5d2e3424367f69b92d/src/engine/graph_node.js

]]
GRAPH_RENDER_ACTIVE = bit32.lshift(1, 0)
GRAPH_RENDER_CHILDREN_FIRST = bit32.lshift(1, 1)
GRAPH_RENDER_BILLBOARD = bit32.lshift(1, 2)
GRAPH_RENDER_Z_BUFFER = bit32.lshift(1, 3)
GRAPH_RENDER_INVISIBLE = bit32.lshift(1, 4)
GRAPH_RENDER_HAS_ANIMATION = bit32.lshift(1, 5)
GRAPH_RENDER_CYLBOARD      = bit32.lshift(1, 6)

-- Whether the node type has a function pointer of type GraphNodeFunc
GRAPH_NODE_TYPE_FUNCTIONAL =             0x100

-- Type used for Bowser and an unused geo function in obj_behaviors.c
GRAPH_NODE_TYPE_400    =                 0x400

-- The discriminant for different types of geo nodes
GRAPH_NODE_TYPE_ROOT                   = 0x001
GRAPH_NODE_TYPE_ORTHO_PROJECTION       = 0x002
GRAPH_NODE_TYPE_PERSPECTIVE            = bit32.bor(0x003, GRAPH_NODE_TYPE_FUNCTIONAL)
GRAPH_NODE_TYPE_MASTER_LIST            = 0x004
GRAPH_NODE_TYPE_START                  = 0x00A
GRAPH_NODE_TYPE_LEVEL_OF_DETAIL        = 0x00B
GRAPH_NODE_TYPE_CAMERA                 = bit32.bor(0x014, GRAPH_NODE_TYPE_FUNCTIONAL)
GRAPH_NODE_TYPE_TRANSLATION_ROTATION   = 0x015
GRAPH_NODE_TYPE_TRANSLATION            = 0x016
GRAPH_NODE_TYPE_ROTATION               = 0x017
GRAPH_NODE_TYPE_OBJECT                 = 0x018
GRAPH_NODE_TYPE_ANIMATED_PART          = 0x019
GRAPH_NODE_TYPE_BILLBOARD              = 0x01A
GRAPH_NODE_TYPE_DISPLAY_LIST           = 0x01B
GRAPH_NODE_TYPE_SCALE                  = 0x01C
GRAPH_NODE_TYPE_SHADOW                 = 0x028
GRAPH_NODE_TYPE_OBJECT_PARENT          = 0x029
GRAPH_NODE_TYPE_GENERATED_LIST         = bit32.bor(0x02A, GRAPH_NODE_TYPE_FUNCTIONAL)
GRAPH_NODE_TYPE_BACKGROUND             = bit32.bor(0x02C, GRAPH_NODE_TYPE_FUNCTIONAL)
GRAPH_NODE_TYPE_HELD_OBJ               = bit32.bor(0x02E, GRAPH_NODE_TYPE_FUNCTIONAL)
GRAPH_NODE_TYPE_CULLING_RADIUS         = 0x02F
GRAPH_NODE_TYPE_SWITCH_CASE            = bit32.bor(0x00C, GRAPH_NODE_TYPE_FUNCTIONAL)

local GraphNodeConstats = {
	GRAPH_RENDER_INVISIBLE = GRAPH_RENDER_INVISIBLE,
	GRAPH_RENDER_Z_BUFFER = GRAPH_RENDER_Z_BUFFER,
	GRAPH_RENDER_HAS_ANIMATION = GRAPH_RENDER_HAS_ANIMATION,
	GRAPH_RENDER_CYLBOARD = GRAPH_RENDER_CYLBOARD,
	GRAPH_RENDER_CHILDREN_FIRST = GRAPH_RENDER_CHILDREN_FIRST,
	GRAPH_RENDER_BILLBOARD = GRAPH_RENDER_BILLBOARD,
	GRAPH_RENDER_ACTIVE = GRAPH_RENDER_ACTIVE,
	
	GRAPH_NODE_TYPE_PERSPECTIVE = GRAPH_NODE_TYPE_PERSPECTIVE,
	GRAPH_NODE_TYPE_ROTATION = GRAPH_NODE_TYPE_ROTATION,
	GRAPH_NODE_TYPE_OBJECT_PARENT = GRAPH_NODE_TYPE_OBJECT_PARENT,
	GRAPH_NODE_TYPE_400 = GRAPH_NODE_TYPE_400,
	GRAPH_NODE_TYPE_DISPLAY_LIST = GRAPH_NODE_TYPE_DISPLAY_LIST,
	GRAPH_NODE_TYPE_SWITCH_CASE = GRAPH_NODE_TYPE_SWITCH_CASE,
	GRAPH_NODE_TYPE_BACKGROUND = GRAPH_NODE_TYPE_BACKGROUND,
	GRAPH_NODE_TYPE_CULLING_RADIUS = GRAPH_NODE_TYPE_CULLING_RADIUS,
	GRAPH_NODE_TYPE_ROOT = GRAPH_NODE_TYPE_ROOT,
	GRAPH_NODE_TYPE_SHADOW = GRAPH_NODE_TYPE_SHADOW,
	GRAPH_NODE_TYPE_CAMERA = GRAPH_NODE_TYPE_CAMERA,
	GRAPH_NODE_TYPE_ANIMATED_PART = GRAPH_NODE_TYPE_ANIMATED_PART,
	GRAPH_NODE_TYPE_TRANSLATION_ROTATION = GRAPH_NODE_TYPE_TRANSLATION_ROTATION,
	GRAPH_NODE_TYPE_TRANSLATION = GRAPH_NODE_TYPE_TRANSLATION,
	GRAPH_NODE_TYPE_HELD_OBJ = GRAPH_NODE_TYPE_HELD_OBJ,
	GRAPH_NODE_TYPE_START = GRAPH_NODE_TYPE_START,
	GRAPH_NODE_TYPE_LEVEL_OF_DETAIL = GRAPH_NODE_TYPE_LEVEL_OF_DETAIL,
	GRAPH_NODE_TYPE_SCALE = GRAPH_NODE_TYPE_SCALE,
	GRAPH_NODE_TYPE_BILLBOARD = GRAPH_NODE_TYPE_BILLBOARD,
	GRAPH_NODE_TYPE_GENERATED_LIST = GRAPH_NODE_TYPE_GENERATED_LIST,
	GRAPH_NODE_TYPE_FUNCTIONAL = GRAPH_NODE_TYPE_FUNCTIONAL,
	GRAPH_NODE_TYPE_ORTHO_PROJECTION = GRAPH_NODE_TYPE_ORTHO_PROJECTION,
	GRAPH_NODE_TYPE_MASTER_LIST = GRAPH_NODE_TYPE_MASTER_LIST,
	GRAPH_NODE_TYPE_OBJECT = GRAPH_NODE_TYPE_OBJECT,
}

return GraphNodeConstats