--!strict

local Folder = setmetatable({}, {
	__index = function(_, k)
		return script:FindFirstChild(k)
	end,
})

-- create sound table
local SoundTable = {
	ACTION_BONK = Folder.ACTION_BONK,
	ACTION_FLYING_FAST = Folder.ACTION_FLYING_FAST,
	ACTION_HIT = Folder.ACTION_HIT,
	ACTION_METAL_BONK = Folder.ACTION_METAL_BONK,
	ACTION_METAL_HEAVY_LANDING = Folder.ACTION_METAL_HEAVY_LANDING,
	ACTION_METAL_LANDING = Folder.ACTION_METAL_LANDING,
	ACTION_METAL_STEP = Folder.ACTION_METAL_STEP,
	ACTION_METAL_JUMP = Folder.ACTION_METAL_JUMP,
	ACTION_PAT_BACK = Folder.ACTION_PAT_BACK,
	ACTION_SIDE_FLIP = Folder.ACTION_SIDE_FLIP,
	ACTION_SPIN = Folder.ACTION_SPIN,
	ACTION_HEAVY_LANDING = Folder.ACTION_HEAVY_LANDING,
	ACTION_TERRAIN_BODY_HIT_GROUND = Folder.ACTION_TERRAIN_BODY_HIT_GROUND,
	ACTION_TERRAIN_JUMP = Folder.ACTION_TERRAIN_JUMP,
	ACTION_TERRAIN_LANDING = Folder.ACTION_TERRAIN_LANDING,
	ACTION_TERRAIN_STEP = Folder.ACTION_TERRAIN_STEP,
	ACTION_THROW = Folder.ACTION_THROW,
	ACTION_TWIRL = Folder.ACTION_TWIRL,

	ACTION_METAL_LAND_WATER = Folder.ACTION_METAL_LAND_WATER,
	ACTION_METAL_JUMP_WATER = Folder.ACTION_METAL_LAND_WATER,
	ACTION_WATER_ENTER = Folder.ACTION_WATER_ENTER,
	ACTION_WATER_EXIT = Folder.ACTION_WATER_EXIT,
	ACTION_SWIM_KICK = Folder.ACTION_SWIM_KICK,
	ACTION_SWIM_FAST = Folder.ACTION_SWIM_FAST,
	ACTION_SWIM = Folder.ACTION_SWIM,

	MARIO_ATTACKED = Folder.MARIO_ATTACKED,
	MARIO_DOH = Folder.MARIO_DOH,
	MARIO_GROUND_POUND_WAH = Folder.MARIO_GROUND_POUND_WAH,
	MARIO_HAHA = Folder.MARIO_HAHA,
	MARIO_HOO = Folder.MARIO_HOO,
	MARIO_HOOHOO = Folder.MARIO_HOOHOO,
	MARIO_IMA_TIRED = Folder.MARIO_IMA_TIRED,
	MARIO_MAMA_MIA = Folder.MARIO_MAMA_MIA,
	MARIO_ON_FIRE = Folder.MARIO_ON_FIRE,
	MARIO_OOOF = Folder.MARIO_OOOF,
	MARIO_PANTING = Folder.MARIO_PANTING,
	MARIO_PUNCH_YAH = Folder.MARIO_PUNCH_YAH,
	MARIO_PUNCH_WAH = Folder.MARIO_PUNCH_WAH,
	MARIO_PUNCH_HOO = Folder.MARIO_PUNCH_HOO,
	MARIO_SNORING1 = Folder.MARIO_SNORING1,
	MARIO_SNORING2 = Folder.MARIO_SNORING2,
	MARIO_SNORING3 = Folder.MARIO_SNORING3,
	MARIO_UH = Folder.MARIO_UH,
	MARIO_UH2 = Folder.MARIO_UH2,
	MARIO_WAAAOOOW = Folder.MARIO_WAAAOOOW,
	MARIO_WAH = Folder.MARIO_WAH,
	MARIO_WAHA = Folder.MARIO_WAHA,
	MARIO_WHOA = Folder.MARIO_WHOA,
	MARIO_YAH = Folder.MARIO_YAH,
	MARIO_YAHOO = Folder.MARIO_YAHOO,
	MARIO_YAWNING = Folder.MARIO_YAWNING,
	MARIO_YIPPEE = Folder.MARIO_YIPPEE,

	MOVING_FLYING = Folder.MOVING_FLYING,
	MOVING_LAVA_BURN = Folder.MOVING_LAVA_BURN,
	MOVING_TERRAIN_SLIDE = Folder.MOVING_TERRAIN_SLIDE,

	MARIO_JUMP = Folder.MARIO_JUMP,
	MARIO_YAH_WAH_HOO = Folder.MARIO_YAH_WAH_HOO,
	MARIO_YAHOO_WAHA_YIPPEE = Folder.MARIO_YAHOO_WAHA_YIPPEE,

	ACTION_TERRAIN_STEP_DEFAULT = Folder.ACTION_TERRAIN_STEP_DEFAULT,
	ACTION_TERRAIN_STEP_GRASS = Folder.ACTION_TERRAIN_STEP_GRASS,
	ACTION_TERRAIN_STEP_ICE = Folder.ACTION_TERRAIN_STEP_ICE,
	ACTION_TERRAIN_STEP_METAL = Folder.ACTION_TERRAIN_STEP_METAL,
	ACTION_TERRAIN_STEP_SAND = Folder.ACTION_TERRAIN_STEP_SAND,
	ACTION_TERRAIN_STEP_SNOW = Folder.ACTION_TERRAIN_STEP_SNOW,
	ACTION_TERRAIN_STEP_SPOOKY = Folder.ACTION_TERRAIN_STEP_SPOOKY,
	ACTION_TERRAIN_STEP_STONE = Folder.ACTION_TERRAIN_STEP_STONE,

	ACTION_TERRAIN_LANDING_DEFAULT = Folder.ACTION_TERRAIN_LANDING_DEFAULT,
	ACTION_TERRAIN_LANDING_GRASS = Folder.ACTION_TERRAIN_LANDING_GRASS,
	ACTION_TERRAIN_LANDING_ICE = Folder.ACTION_TERRAIN_LANDING_ICE,
	ACTION_TERRAIN_LANDING_METAL = Folder.ACTION_TERRAIN_LANDING_METAL,
	ACTION_TERRAIN_LANDING_SAND = Folder.ACTION_TERRAIN_LANDING_SAND,
	ACTION_TERRAIN_LANDING_SNOW = Folder.ACTION_TERRAIN_LANDING_SNOW,
	ACTION_TERRAIN_LANDING_SPOOKY = Folder.ACTION_TERRAIN_LANDING_SPOOKY,
	ACTION_TERRAIN_LANDING_STONE = Folder.ACTION_TERRAIN_LANDING_STONE,

	ACTION_TERRAIN_JUMP_DEFAULT = Folder.ACTION_TERRAIN_LANDING_DEFAULT,
	ACTION_TERRAIN_JUMP_GRASS = Folder.ACTION_TERRAIN_LANDING_GRASS,
	ACTION_TERRAIN_JUMP_ICE = Folder.ACTION_TERRAIN_LANDING_ICE,
	ACTION_TERRAIN_JUMP_METAL = Folder.ACTION_TERRAIN_LANDING_METAL,
	ACTION_TERRAIN_JUMP_SAND = Folder.ACTION_TERRAIN_LANDING_SAND,
	ACTION_TERRAIN_JUMP_SNOW = Folder.ACTION_TERRAIN_LANDING_SNOW,
	ACTION_TERRAIN_JUMP_SPOOKY = Folder.ACTION_TERRAIN_LANDING_SPOOKY,
	ACTION_TERRAIN_JUMP_STONE = Folder.ACTION_TERRAIN_LANDING_STONE,
} :: {[string]: Sound | Configuration}
for _, instance in pairs(script:GetChildren()) do
	if (instance:IsA("Sound") or instance:IsA("Configuration")) and not SoundTable[instance.Name] then
		SoundTable[instance.Name] = instance
	end
end

-- create voicetable
local VoiceTable = {} :: {[string]: Sound | Configuration}

local function validateVoiceTableSound(k: string)
	if k:sub(1, 5) == 'MARIO' then
		VoiceTable[k] = SoundTable[k]
	end
end

for k in pairs(SoundTable) do
	validateVoiceTableSound(k)
end

-- treat missing sounds
local UNKOWN_CACHE = {}
setmetatable(SoundTable, {
	__index = function(_, k)
		local any = script:FindFirstChild(k, true)
		if any then
			rawset(SoundTable, k, any)
			UNKOWN_CACHE[k] = nil
			return any
		end
		if UNKOWN_CACHE[k] then
			return
		end
		warn("[!] Unknown sound:", k)
		UNKOWN_CACHE[k] = true
		return nil
	end,
})

return {
	SoundTable = SoundTable,
	VoiceTable = VoiceTable,
}