--!strict

-- TODO: give this a better name lol
local Folder = setmetatable({}, {
	__index = function(_, k)
		return script:FindFirstChild(k)
	end,
})

local AnimTable = {
	SLOW_LEDGE_GRAB = Folder.SLOW_LEDGE_GRAB,
	FALL_OVER_BACKWARDS = Folder.FALL_OVER_BACKWARDS,
	BACKWARD_AIR_KB = Folder.BACKWARD_AIR_KB,
	DYING_ON_BACK = Folder.DYING_ON_BACK,
	BACKFLIP = Folder.BACKFLIP,
	CLIMB_UP_POLE = Folder.CLIMB_UP_POLE,
	GRAB_POLE_SHORT = Folder.GRAB_POLE_SHORT,
	GRAB_POLE_SWING_PART1 = Folder.GRAB_POLE_SWING_PART1,
	GRAB_POLE_SWING_PART2 = Folder.GRAB_POLE_SWING_PART2,
	HANDSTAND_IDLE = Folder.HANDSTAND_IDLE,
	HANDSTAND_JUMP = Folder.HANDSTAND_JUMP,
	START_HANDSTAND = Folder.START_HANDSTAND,
	RETURN_FROM_HANDSTAND = Folder.RETURN_FROM_HANDSTAND,
	IDLE_ON_POLE = Folder.IDLE_ON_POLE,
	A_POSE = Folder.A_POSE,
	SKID_ON_GROUND = Folder.SKID_ON_GROUND,
	STOP_SKID = Folder.STOP_SKID,
	CROUCH_FROM_FAST_LONGJUMP = Folder.CROUCH_FROM_FAST_LONGJUMP,
	CROUCH_FROM_SLOW_LONGJUMP = Folder.CROUCH_FROM_SLOW_LONGJUMP,
	FAST_LONGJUMP = Folder.FAST_LONGJUMP,
	SLOW_LONGJUMP = Folder.SLOW_LONGJUMP,
	AIRBORNE_ON_STOMACH = Folder.AIRBORNE_ON_STOMACH,
	WALK_WITH_LIGHT_OBJ = Folder.WALK_WITH_LIGHT_OBJ,
	RUN_WITH_LIGHT_OBJ = Folder.RUN_WITH_LIGHT_OBJ,
	SLOW_WALK_WITH_LIGHT_OBJ = Folder.SLOW_WALK_WITH_LIGHT_OBJ,
	SHIVERING_WARMING_HAND = Folder.SHIVERING_WARMING_HAND,
	SHIVERING_RETURN_TO_IDLE = Folder.SHIVERING_RETURN_TO_IDLE,
	SHIVERING = Folder.SHIVERING,
	CLIMB_DOWN_LEDGE = Folder.CLIMB_DOWN_LEDGE,
	CREDITS_WAVING = Folder.CREDITS_WAVING,
	CREDITS_LOOK_UP = Folder.CREDITS_LOOK_UP,
	CREDITS_RETURN_FROM_LOOK_UP = Folder.CREDITS_RETURN_FROM_LOOK_UP,
	CREDITS_RAISE_HAND = Folder.CREDITS_RAISE_HAND,
	CREDITS_LOWER_HAND = Folder.CREDITS_LOWER_HAND,
	CREDITS_TAKE_OFF_CAP = Folder.CREDITS_TAKE_OFF_CAP,
	CREDITS_START_WALK_LOOK_UP = Folder.CREDITS_START_WALK_LOOK_UP,
	CREDITS_LOOK_BACK_THEN_RUN = Folder.CREDITS_LOOK_BACK_THEN_RUN,
	--	FINAL_BOWSER_RAISE_HAND_SPIN = Folder.FINAL_BOWSER_RAISE_HAND_SPIN;
	--	FINAL_BOWSER_WING_CAP_TAKE_OFF = Folder.FINAL_BOWSER_WING_CAP_TAKE_OFF;
	CREDITS_PEACE_SIGN = Folder.CREDITS_PEACE_SIGN,
	STAND_UP_FROM_LAVA_BOOST = Folder.STAND_UP_FROM_LAVA_BOOST,
	FIRE_LAVA_BURN = Folder.FIRE_LAVA_BURN,
	WING_CAP_FLY = Folder.WING_CAP_FLY,
	HANG_ON_OWL = Folder.HANG_ON_OWL,
	LAND_ON_STOMACH = Folder.LAND_ON_STOMACH,
	FORWARD_AIR_KB = Folder.FORWARD_AIR_KB,
	DYING_ON_STOMACH = Folder.DYING_ON_STOMACH,
	SUFFOCATING = Folder.SUFFOCATING,
	COUGHING = Folder.COUGHING,
	THROW_CATCH_KEY = Folder.THROW_CATCH_KEY,
	DYING_FALL_OVER = Folder.DYING_FALL_OVER,
	IDLE_ON_LEDGE = Folder.IDLE_ON_LEDGE,
	FAST_LEDGE_GRAB = Folder.FAST_LEDGE_GRAB,
	HANG_ON_CEILING = Folder.HANG_ON_CEILING,
	PUT_CAP_ON = Folder.PUT_CAP_ON,
	TAKE_CAP_OFF_THEN_ON = Folder.TAKE_CAP_OFF_THEN_ON,
	QUICKLY_PUT_CAP_ON = Folder.QUICKLY_PUT_CAP_ON, -- unused
	HEAD_STUCK_IN_GROUND = Folder.HEAD_STUCK_IN_GROUND,
	GROUND_POUND_LANDING = Folder.GROUND_POUND_LANDING,
	TRIPLE_JUMP_GROUND_POUND = Folder.TRIPLE_JUMP_GROUND_POUND,
	START_GROUND_POUND = Folder.START_GROUND_POUND,
	GROUND_POUND = Folder.GROUND_POUND,
	BOTTOM_STUCK_IN_GROUND = Folder.BOTTOM_STUCK_IN_GROUND,
	IDLE_WITH_LIGHT_OBJ = Folder.IDLE_WITH_LIGHT_OBJ,
	JUMP_LAND_WITH_LIGHT_OBJ = Folder.JUMP_LAND_WITH_LIGHT_OBJ,
	JUMP_WITH_LIGHT_OBJ = Folder.JUMP_WITH_LIGHT_OBJ,
	FALL_LAND_WITH_LIGHT_OBJ = Folder.FALL_LAND_WITH_LIGHT_OBJ,
	FALL_WITH_LIGHT_OBJ = Folder.FALL_WITH_LIGHT_OBJ,
	FALL_FROM_SLIDING_WITH_LIGHT_OBJ = Folder.FALL_FROM_SLIDING_WITH_LIGHT_OBJ,
	SLIDING_ON_BOTTOM_WITH_LIGHT_OBJ = Folder.SLIDING_ON_BOTTOM_WITH_LIGHT_OBJ,
	STAND_UP_FROM_SLIDING_WITH_LIGHT_OBJ = Folder.STAND_UP_FROM_SLIDING_WITH_LIGHT_OBJ,
	RIDING_SHELL = Folder.RIDING_SHELL,
	WALKING = Folder.WALKING,
	FORWARD_FLIP = Folder.FORWARD_FLIP, -- unused
	JUMP_RIDING_SHELL = Folder.JUMP_RIDING_SHELL,
	LAND_FROM_DOUBLE_JUMP = Folder.LAND_FROM_DOUBLE_JUMP,
	DOUBLE_JUMP_FALL = Folder.DOUBLE_JUMP_FALL,
	SINGLE_JUMP = Folder.SINGLE_JUMP,
	LAND_FROM_SINGLE_JUMP = Folder.LAND_FROM_SINGLE_JUMP,
	AIR_KICK = Folder.AIR_KICK,
	DOUBLE_JUMP_RISE = Folder.DOUBLE_JUMP_RISE,
	START_FORWARD_SPINNING = Folder.START_FORWARD_SPINNING, -- unused
	THROW_LIGHT_OBJECT = Folder.THROW_LIGHT_OBJECT,
	FALL_FROM_SLIDE_KICK = Folder.FALL_FROM_SLIDE_KICK,
	BEND_KNESS_RIDING_SHELL = Folder.BEND_KNESS_RIDING_SHELL, -- unused
	LEGS_STUCK_IN_GROUND = Folder.LEGS_STUCK_IN_GROUND,
	GENERAL_FALL = Folder.GENERAL_FALL,
	GENERAL_LAND = Folder.GENERAL_LAND,
	BEING_GRABBED = Folder.BEING_GRABBED,
	GRAB_HEAVY_OBJECT = Folder.GRAB_HEAVY_OBJECT,
	SLOW_LAND_FROM_DIVE = Folder.SLOW_LAND_FROM_DIVE,
	FLY_FROM_CANNON = Folder.FLY_FROM_CANNON,
	MOVE_ON_WIRE_NET_RIGHT = Folder.MOVE_ON_WIRE_NET_RIGHT,
	MOVE_ON_WIRE_NET_LEFT = Folder.MOVE_ON_WIRE_NET_LEFT,
	MISSING_CAP = Folder.MISSING_CAP,
	PULL_DOOR_WALK_IN = Folder.PULL_DOOR_WALK_IN,
	PUSH_DOOR_WALK_IN = Folder.PUSH_DOOR_WALK_IN,
	UNLOCK_DOOR = Folder.UNLOCK_DOOR,
	START_REACH_POCKET = Folder.START_REACH_POCKET, -- unused, reaching keys maybe?
	REACH_POCKET = Folder.REACH_POCKET, -- unused
	STOP_REACH_POCKET = Folder.STOP_REACH_POCKET, -- unused
	GROUND_THROW = Folder.GROUND_THROW,
	GROUND_KICK = Folder.GROUND_KICK,
	FIRST_PUNCH = Folder.FIRST_PUNCH,
	SECOND_PUNCH = Folder.SECOND_PUNCH,
	FIRST_PUNCH_FAST = Folder.FIRST_PUNCH_FAST,
	SECOND_PUNCH_FAST = Folder.SECOND_PUNCH_FAST,
	PICK_UP_LIGHT_OBJ = Folder.PICK_UP_LIGHT_OBJ,
	PUSHING = Folder.PUSHING,
	START_RIDING_SHELL = Folder.START_RIDING_SHELL,
	PLACE_LIGHT_OBJ = Folder.PLACE_LIGHT_OBJ,
	FORWARD_SPINNING = Folder.FORWARD_SPINNING,
	BACKWARD_SPINNING = Folder.BACKWARD_SPINNING,
	BREAKDANCE = Folder.BREAKDANCE,
	RUNNING = Folder.RUNNING,
	RUNNING_UNUSED = Folder.RUNNING_UNUSED, -- unused duplicate, originally part 2?
	SOFT_BACK_KB = Folder.SOFT_BACK_KB,
	SOFT_FRONT_KB = Folder.SOFT_FRONT_KB,
	DYING_IN_QUICKSAND = Folder.DYING_IN_QUICKSAND,
	IDLE_IN_QUICKSAND = Folder.IDLE_IN_QUICKSAND,
	MOVE_IN_QUICKSAND = Folder.MOVE_IN_QUICKSAND,
	ELECTROCUTION = Folder.ELECTROCUTION,
	SHOCKED = Folder.SHOCKED,
	BACKWARD_KB = Folder.BACKWARD_KB,
	FORWARD_KB = Folder.FORWARD_KB,
	IDLE_HEAVY_OBJ = Folder.IDLE_HEAVY_OBJ,
	STAND_AGAINST_WALL = Folder.STAND_AGAINST_WALL,
	SIDESTEP_LEFT = Folder.SIDESTEP_LEFT,
	SIDESTEP_RIGHT = Folder.SIDESTEP_RIGHT,
	START_SLEEP_IDLE = Folder.START_SLEEP_IDLE,
	START_SLEEP_SCRATCH = Folder.START_SLEEP_SCRATCH,
	START_SLEEP_YAWN = Folder.START_SLEEP_YAWN,
	START_SLEEP_SITTING = Folder.START_SLEEP_SITTING,
	SLEEP_IDLE = Folder.SLEEP_IDLE,
	SLEEP_START_LYING = Folder.SLEEP_START_LYING,
	SLEEP_LYING = Folder.SLEEP_LYING,
	DIVE = Folder.DIVE,
	SLIDE_DIVE = Folder.SLIDE_DIVE,
	GROUND_BONK = Folder.GROUND_BONK,
	STOP_SLIDE_LIGHT_OBJ = Folder.STOP_SLIDE_LIGHT_OBJ,
	SLIDE_KICK = Folder.SLIDE_KICK,
	CROUCH_FROM_SLIDE_KICK = Folder.CROUCH_FROM_SLIDE_KICK,
	SLIDE_MOTIONLESS = Folder.SLIDE_MOTIONLESS, -- unused
	STOP_SLIDE = Folder.STOP_SLIDE,
	FALL_FROM_SLIDE = Folder.FALL_FROM_SLIDE,
	SLIDE = Folder.SLIDE,
	TIPTOE = Folder.TIPTOE,
	TWIRL_LAND = Folder.TWIRL_LAND,
	TWIRL = Folder.TWIRL,
	START_TWIRL = Folder.START_TWIRL,
	STOP_CROUCHING = Folder.STOP_CROUCHING,
	START_CROUCHING = Folder.START_CROUCHING,
	CROUCHING = Folder.CROUCHING,
	CRAWLING = Folder.CRAWLING,
	STOP_CRAWLING = Folder.STOP_CRAWLING,
	START_CRAWLING = Folder.START_CRAWLING,
	SUMMON_STAR = Folder.SUMMON_STAR,
	RETURN_STAR_APPROACH_DOOR = Folder.RETURN_STAR_APPROACH_DOOR,
	BACKWARDS_WATER_KB = Folder.BACKWARDS_WATER_KB,
	SWIM_WITH_OBJ_PART1 = Folder.SWIM_WITH_OBJ_PART1,
	SWIM_WITH_OBJ_PART2 = Folder.SWIM_WITH_OBJ_PART2,
	FLUTTERKICK_WITH_OBJ = Folder.FLUTTERKICK_WITH_OBJ,
	WATER_ACTION_END_WITH_OBJ = Folder.WATER_ACTION_END_WITH_OBJ, -- either swimming or flutterkicking
	STOP_GRAB_OBJ_WATER = Folder.STOP_GRAB_OBJ_WATER,
	WATER_IDLE_WITH_OBJ = Folder.WATER_IDLE_WITH_OBJ,
	DROWNING_PART1 = Folder.DROWNING_PART1,
	DROWNING_PART2 = Folder.DROWNING_PART2,
	WATER_DYING = Folder.WATER_DYING,
	WATER_FORWARD_KB = Folder.WATER_FORWARD_KB,
	FALL_FROM_WATER = Folder.FALL_FROM_WATER,
	SWIM_PART1 = Folder.SWIM_PART1,
	SWIM_PART2 = Folder.SWIM_PART2,
	FLUTTERKICK = Folder.FLUTTERKICK,
	WATER_ACTION_END = Folder.WATER_ACTION_END, -- either swimming or flutterkicking
	WATER_PICK_UP_OBJ = Folder.WATER_PICK_UP_OBJ,
	WATER_GRAB_OBJ_PART2 = Folder.WATER_GRAB_OBJ_PART2,
	WATER_GRAB_OBJ_PART1 = Folder.WATER_GRAB_OBJ_PART1,
	WATER_THROW_OBJ = Folder.WATER_THROW_OBJ,
	WATER_IDLE = Folder.WATER_IDLE,
	WATER_STAR_DANCE = Folder.WATER_STAR_DANCE,
	RETURN_FROM_WATER_STAR_DANCE = Folder.RETURN_FROM_WATER_STAR_DANCE,
	--	GRAB_BOWSER = Folder.GRAB_BOWSER;
	--	SWINGING_BOWSER = Folder.SWINGING_BOWSER;
	--	RELEASE_BOWSER = Folder.RELEASE_BOWSER;
	--	HOLDING_BOWSER = Folder.HOLDING_BOWSER;
	HEAVY_THROW = Folder.HEAVY_THROW,
	WALK_PANTING = Folder.WALK_PANTING,
	WALK_WITH_HEAVY_OBJ = Folder.WALK_WITH_HEAVY_OBJ,
	TURNING_PART1 = Folder.TURNING_PART1,
	TURNING_PART2 = Folder.TURNING_PART2,
	SLIDEFLIP_LAND = Folder.SLIDEFLIP_LAND,
	SLIDEFLIP = Folder.SLIDEFLIP,
	TRIPLE_JUMP_LAND = Folder.TRIPLE_JUMP_LAND,
	TRIPLE_JUMP = Folder.TRIPLE_JUMP,
	FIRST_PERSON = Folder.FIRST_PERSON,
	IDLE_HEAD_LEFT = Folder.IDLE_HEAD_LEFT,
	IDLE_HEAD_RIGHT = Folder.IDLE_HEAD_RIGHT,
	IDLE_HEAD_CENTER = Folder.IDLE_HEAD_CENTER,
	HANDSTAND_LEFT = Folder.HANDSTAND_LEFT,
	HANDSTAND_RIGHT = Folder.HANDSTAND_RIGHT,
	WAKE_FROM_SLEEP = Folder.WAKE_FROM_SLEEP,
	WAKE_FROM_LYING = Folder.WAKE_FROM_LYING,
	START_TIPTOE = Folder.START_TIPTOE,
	SLIDEJUMP = Folder.SLIDEJUMP, -- pole jump and wall kick
	START_WALLKICK = Folder.START_WALLKICK,
	STAR_DANCE = Folder.STAR_DANCE,
	RETURN_FROM_STAR_DANCE = Folder.RETURN_FROM_STAR_DANCE,
	FORWARD_SPINNING_FLIP = Folder.FORWARD_SPINNING_FLIP,
	TRIPLE_JUMP_FLY = Folder.TRIPLE_JUMP_FLY,
}

setmetatable(AnimTable, {
	__index = function(_, k)
		local any = script:FindFirstChild(k, true)
		if any then
			rawset(AnimTable, k, any)
			return any
		end
		warn("[!] Unknown ANIMATION:", k)
		return nil
	end,
})

-- preload
task.spawn(function()
	local ContentProvider = game:GetService("ContentProvider")
	local preload = {}

	for _, anim in pairs(AnimTable) do
		table.insert(preload, anim)
	end

	ContentProvider:PreloadAsync(preload)
end)

return AnimTable